export const countries = {
  "The Americas": {
    ca: [
      "Vancouver",
      "Toronto",
      "Calgary",
      "Halifax",
      "Ottawa",
      "Montreal",
      "Quebec",
    ],
    mx: [
      "Ciudad Juarez",
      "Guadalajara",
      "Hermosillo",
      "Matamoros",
      "Merida",
      "Mexico City",
      "Monterrey",
      "Nogales",
      "Nuevo Laredo",
      "Tijuana",
    ],
    cl: ["Santiago"],
    br: ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Recife", "Porto Alegre"],
    ar: ["Buenos Aires"],
    bs: ["Nassau"],
    bb: ["Bridgetown"],
    bz: ["Belmopan"],
    bo: ["La Paz"],
    co: ["Bogota"],
    cw: ["Curacao"],
    ec: ["Guayaquil", "Quito"],
    gy: ["Georgetown"],
    jm: ["Kingston"],
    py: ["Asuncion"],
    pe: ["Lima"],
    sr: ["Paramaribo"],
    tt: ["Port of Spain"],
    uy: ["Montevideo"],
  },
  Europe: {
    gb: ["London", "Belfast"],
    fr: ["Paris"],
    es: ["Madrid"],
    it: ["Rome", "Florence", "Milan", "Naples"],
    al: ["Tirana"],
    am: ["Yerevan"],
    az: ["Baku"],
    ba: ["Sarajevo"],
    be: ["Brussels"],
    hr: ["Zagreb"],
    xk: ["Pristina"],
    nl: ["Amsterdam"],
    ie: ["Dublin"],
    mk: ["Skopje"],
    gr: ["Athens"],
    cy: ["Nicosia", "North"],
    rs: ["Belgrade"],
    pt: ["Lisbon"],
    tr: ["Ankara", "Istanbul"],
  },
  Asia: {
    ae: ["Abu Dhabi", "Dubai"],
    cn: [],
  },
};

export const abbr = {
  "The Americas": "ta",
  Europe: "eu",
  Asia: "as",
};

export const countryMap = {
  ca: ["The Americas", "ais", "Canada", "加拿大"],
  gb: ["Europe", "ais", "United Kingdom", "英国"],
  fr: ["Europe", "ais", "France", "法国"],
  es: ["Europe", "ais", "Spain and Andorra", "西班牙和安道尔"],
  it: ["Europe", "ais", "Italy", "意大利"],
  al: ["Europe", "ais", "Albania", "阿尔巴尼亚"],
  am: ["Europe", "ais", "Armenia", "亚美尼亚"],
  az: ["Europe", "ais", "Azerbaijan", "阿塞拜疆"],
  ba: ["Europe", "ais", "Bosnia and Herzegovina", "波黑"],
  be: ["Europe", "ais", "Belgium", "比利时"],
  hr: ["Europe", "ais", "Croatia", "克罗地亚"],
  xk: ["Europe", "ais", "Kosovo", "科索沃"],
  nl: ["Europe", "ais", "The Netherlands", "荷兰"],
  ie: ["Europe", "ais", "Ireland", "爱尔兰"],
  mk: ["Europe", "ais", "North Macedonia", "北马其顿"],
  gr: ["Europe", "ais", "Greece", "希腊"],
  cy: ["Europe", "ais", "Cyprus", "塞浦路斯"],
  rs: ["Europe", "ais", "Serbia", "塞尔维亚"],
  ae: ["Asia", "ais", "United Arab Emirates", "阿联酋"],
  cn: ["Asia", "cgi", "China", "中国"],
  mx: ["The Americas", "ais", "Mexico", "墨西哥"],
  cl: ["The Americas", "ais", "Chile", "智利"],
  br: ["The Americas", "ais", "Brazil", "巴西"],
  ar: ["The Americas", "ais", "Argentina", "阿根廷"],
  bs: ["The Americas", "ais", "The Bahamas", "巴哈马"],
  bb: ["The Americas", "ais", "Barbados", "巴巴多斯"],
  bz: ["The Americas", "ais", "Belize", "伯利兹"],
  bo: ["The Americas", "ais", "Bolivia", "玻利维亚"],
  co: ["The Americas", "ais", "Colombia", "哥伦比亚"],
  cw: ["The Americas", "ais", "Curacao", "库拉索"],
  ec: ["The Americas", "ais", "Ecuador", "厄瓜多尔"],
  gy: ["The Americas", "ais", "Guyana", "圭亚那"],
  jm: ["The Americas", "ais", "Jamaica", "牙买加"],
  py: ["The Americas", "ais", "Paraguay", "巴拉圭"],
  pe: ["The Americas", "ais", "Peru", "秘鲁"],
  sr: ["The Americas", "ais", "Suriname", "苏里南"],
  tt: ["The Americas", "ais", "Trinidad and Tobago", "特立尼达和多巴哥"],
  uy: ["The Americas", "ais", "Uruguay", "乌拉圭"],
  pt: ["Europe", "ais", "Portugal", "葡萄牙"],
  tr: ["Europe", "ais", "Turkey", "土耳其"],
};
